# Generated by Django 4.1.3 on 2022-12-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="percent",
            field=models.IntegerField(default=0, verbose_name="Процент"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="salary",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Оклад"
            ),
        ),
    ]
