# Generated by Django 4.1.3 on 2022-12-11 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_percent_customuser_salary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="название филиала"),
                ),
                (
                    "address",
                    models.CharField(max_length=255, verbose_name="Адрес Филиала"),
                ),
                (
                    "cashbox",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=50,
                        max_length=20,
                        verbose_name="Касса",
                    ),
                ),
                (
                    "outcome",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=50,
                        max_length=20,
                        verbose_name="Расходы",
                    ),
                ),
                (
                    "income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=50,
                        max_length=20,
                        verbose_name="Доход",
                    ),
                ),
            ],
            options={
                "verbose_name": "Филиал",
                "verbose_name_plural": "Филиалы",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название Группы"),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "phone_number",
                    models.CharField(max_length=50, verbose_name="Номер Телефона"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.group",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
    ]
